### PR TITLE
Update checkstyle version to match Duke

### PR DESCRIPTION
**Pull request by j-lum**
Let's make the version of checkstyle consistent across projects.
Bump checkstyle to version 8.23.
Remove references to FileContentsHolder as it has been removed in v8.2.

### CODE REVIEW

**Comment by damithc** [comment]
@j-lum Let me know when ready for review

**Comment by damithc** [comment]
@j-lum confirmed this config file works for IDEA as well? IIRC, that's where the version incompatibility caused problems.

**Comment by j-lum** [comment]
Since there are a lot breaking changes to JavaDoc checks, I've updated them to match the latest version. There are some rules that don't have a direct 1-to-1 replacement but those don't seem to affect our code base much. (See for details: https://github.com/checkstyle/checkstyle/issues/7329) 

I've also added a check for `InvalidJavaDocPosition` which actually caught one such comment in one of our tests. 
When this gets merged I'll port over the checkstyle rules to Duke to ensure consistency. 

Also I've tested that the config file can be imported into the plugin and all inspections work.
image

**Review by damithc — CHANGES_REQUESTED** [review]
I'm OK with the changes. This change is significant enough to warrant a proper commit message as per SE-EDU commit message standards. Can update the commit message?

**Pull request merged**
