### PR TITLE
Rephrase 'file not found' logs shown during first run #139

### LINKED ISSUE #139: Rephrase 'file not found' logs shown during first run
When the app is run for the first time, the log shows some 'file not found' messages that some might interpret as errors. 

image

Suggestion: We can rephrase them to appear less like an error message.

### PR DESCRIPTION
**Pull request by LimJunxue**
Fixes #139 
Result:

image

### CODE REVIEW

**Comment by damithc** [comment]
@LimJunxue the log messages that caused the initial confusion are still there. Can we _replace_  (rather than add onto) those messages with the new messages?

**Comment by LimJunxue** [comment]
@damithc hmm the `Json file ... not found.` log comes from `JsonUtil#readJsonFile` which does not create the new files though. Will it be better if we change the `Config file not found. Will be starting with a new default config file.` lines to `Config file not yet **created**. Will be starting with a new default config file.` while still keeping the JsonUtil log?

**Comment by damithc** [comment]
> @damithc hmm the `Json file ... not found.` log comes from `JsonUtil#readJsonFile` which does not create the new files though.

I see. We can try lowering the log level of the initial log message e.g., `logger.fine` so that it appears only for developers specifically running the app at a lower lower log level (assuming the default log level is `info`). If that doesn't work, we can also consider removing it altogether. What do you think?

**Comment by LimJunxue** [comment]
The changing of log level issue is still unfixed which might cause some confusion for developers. So I think removing the log is fine too because it is not needed when the added logs covers all uses of `JsonUtil#readJsonFile` in this project.

**Comment by damithc** [comment]
> The changing of log level issue is still unfixed which might cause some confusion for developers.

Are you sure? When I changed the line as follows, it doesn't appear in the console anymore.

```java
logger.fine("Json file " + filePath + " not found");
```

But you are right in that developers might be confused if they don't know that `fine` level log messages don't appear by default.

Another option is to report when the file is found, rather than not found:
```java
        if (!Files.exists(filePath)) {
            return Optional.empty();
        }
        logger.info("Json file " + filePath + " found");
```

**Comment by LimJunxue** [comment]
> The changing of log level issue is still unfixed which might cause some confusion for developers.

This was referring to #126 

The result will be this, is this ok?
image

**Comment by damithc** [comment]
> The result will be this, is this ok?
> image

@LimJunxue This one is OK. The more interesting one is the case of the file not being found. That's the one that confused students.

**Comment by damithc** [comment]
@se-edu/tech-team-level1 for your review ...

**Review by Hikoya — APPROVED** [review]
LGTM. The new logs are much more clearer to understand.

**Comment by damithc** [comment]
Sorry, it took a while for me to come back to this PR.
I'm wondering if including the target filename in the log message is better (rather than the current `Prefs file not found. ...`, `Preferences file prefs.json not found. ...`)

**Comment by damithc** [comment]
Closing in favor of #170

**Pull request closed without merging**
