### PR TITLE
Reintroduce repo-wide checks

### PR DESCRIPTION
**Pull request by j-lum**
As repository-wide checks were not ported over during the migration from
Travis to GitHub Actions, let's reintroduce them.

Also, let's fix some of the formatting errors in the documentation that were
caught by the tests.

### CODE REVIEW

**Comment by j-lum** [comment]
Bot appears to be down.

**Review by damithc — CHANGES_REQUESTED** [review]
Can add documentation too? reference: https://github.com/nus-cs2103-AY1920S2/addressbook-level3/blob/master/docs/UsingTravis.adoc#repository-wide-checks

Don't forget to use `Fixex #1234` in the PR description.

**Comment by damithc** [comment]
@j-lum reminder

**Comment by j-lum** [comment]
Think we are good to go on this here.

**Comment by damithc** [comment]
Fixes part of #42, documentation yet to be added

**Pull request merged**
