### PR TITLE
Fix miscellaneous typos

### LINKED ISSUE #52: Typos
In AB3's [CommitActivityDiagram](https://github.com/se-edu/addressbook-level3/blob/master/docs/images/CommitActivityDiagram.png), `Purge redunant states` should be `Purge redundant states`

In AB3's [Add Remark Tutorial](https://github.com/se-edu/addressbook-level3/blob/master/docs/tutorials/AddRemark.md) `throw an CommandException` should be `throw a CommandException`, and `Remark has no constrains` should be `Remark has no constraints`

### PR DESCRIPTION
**Pull request by wltan**
Fixes #52

### CODE REVIEW

**Comment by damithc** [comment]
@wltan 
1. As these are two different fixes, I think the PR should be split into two commits.
2. The change to the activity diagram also requires an updated png file? (@j-lum correct me if wrong).

**Comment by wltan** [comment]
> 1. As these are two different fixes, I think the PR should be split into two commits.

Ok, I've split the changes over two commits, each with a simple message body as well.

> 2. The change to the activity diagram also requires an updated png file?

I've already created and pushed a new png for the updated diagram. Do any further changes need to be made?

**Comment by damithc** [comment]
@wltan if ready for review, you can use the bot to submit a new version (use the same link as before).

**Review by damithc — CHANGES_REQUESTED** [review]
Good. Some suggestions:

[v2 1/2] Fix typo in CommitActivityDiagram

* Commit message: 
   * body: no need to mention updating the diagram, as it is _expected_.
   * subject: `... in CommitActivityDiagram.puml`? 
     or `CommitActivityDiagram.puml: Fix typo redunant -> redundant`

[v2 2/2] Fix typo in Add Remark Tutorial

* commit message: tweak to be similar to 1/1.

**Review by damithc — APPROVED** [review]
LGTM

**Comment by damithc** [comment]
Thanks for the fixes @wltan

**Pull request merged**
