### PR TITLE
Missing inheritance in Storage class diagram #90

### LINKED ISSUE #90: Missing inheritance in Storage class diagram
See https://github.com/nus-cs2103-AY2021S2/forum/issues/224#issuecomment-796444725

### PR DESCRIPTION
**Pull request by seanjyjy**
Fixes #90 

updated class diagram:
StorageClassDiagram

### CODE REVIEW

**Comment by damithc** [comment]
Thanks for the fix @seanjyjy 
Follow instructions in https://github.com/se-edu/addressbook-level3/pull/91#issuecomment-810761801 when the PR is ready for review

**Comment by damithc** [comment]
> Follow instructions in [#91 (comment)](https://github.com/se-edu/addressbook-level3/pull/91#issuecomment-810761801) when the PR is ready for review

Sorry, you've done that already.

@se-edu/tech-team-level1  for your review please.

**Comment by RuiFengg** [comment]
LGTM, diagram shows Storage inheriting from UserPrefsStorage and AddressBookStorage
Edit: Commit message could be more specific to describe the fix

> > Follow instructions in [#91 (comment)](https://github.com/se-edu/addressbook-level3/pull/91#issuecomment-810761801) when the PR is ready for review
> 
> Sorry, you've done that already.
> 
> @se-edu/tech-team-level1 for your review please.

**Comment by seanjyjy** [comment]
Thanks for the review, @RuiFengg  The suggested changes to the commit message has been changed.

**Comment by damithc** [comment]
Thanks again both. Did some further revisions to the commit message before merging.

**Pull request merged**
