### PR TITLE
Upgrade Gradle to 7.4.2

### LINKED ISSUE #123: Upgrade Gradle to 7.4
In the [Gradle Compatibility Matrix](https://docs.gradle.org/current/userguide/compatibility.html), it is mentioned that the first Gradle version to support Java 17 is 7.3. However, 7.4 is the latest version.

In line with a future migration to Java 17, I propose upgrading Gradle first.

### PR DESCRIPTION
**Pull request by yhtMinceraft1010X**
Fixes #123

Properties marked as deprecated and to be removed in a future `Gradle 8.0` are also changed.

### CODE REVIEW

**Comment by fans2619** [comment]
@damithc Hi prof, there seems to be some PRs going on here for upgrading different tools. Some seems to be pre-requisites of upgrading Java (e.g., this upgrade of gradle to 7.4.2). Do you want to merge them?

By the way, the app seems able to run when I simply change to Java 17. 😅

**Comment by damithc** [comment]
Thanks for the PR @yhtMinceraft1010X and thanks for the reminder @fans2619 

@yhtMinceraft1010X I assume all the changes in this commit are interrelated and cannot be done as multiple independent steps (and hence, multiple commits)?

@se-edu/tech-team-level1 for your review please

**Comment by kouyk** [comment]
I performed the upgrade process separately, following instructions in https://docs.gradle.org/current/userguide/upgrading_version_5.html and https://docs.gradle.org/current/userguide/upgrading_version_6.html to perform the necessary checks. The properties updated in this PR are the only ones I found necessary as well.

Not sure how @yhtMinceraft1010X performed the upgrades, for myself I ran `gradle wrapper --gradle-version 6.9.2` and `gradle wrapper --gradle-version 7.4.2`. Several gradle wrapper scripts and jars have been updated as well, which were not included in this PR. See [my branch](https://github.com/kouyk/addressbook-level3/tree/gradle-upgrade) for the details.

I can confirm that it is necessary to bump Gradle Shadow together with Gradle, due to deprecations and some incompatibilities I have outlined in my commits.

> I assume all the changes in this commit are interrelated and cannot be done as multiple independent steps (and hence, multiple commits)?

The only question is whether to bump Gradle directly to v7 or perform the upgrade step by step and commit them separately.

**Comment by damithc** [comment]
@yhtMinceraft1010X and others, what do you guys think? Do the 'full' upgrade in two steps as @kouyk mentioned or do a minimal one-step upgrade as done in this PR? What are the pros and cons?

**Comment by yhtMinceraft1010X** [comment]
I tried running `gradlew wrapper --gradle-version 7.4.2` again and there were some additional changes with respect to the wrapper scripts and the jar file.

I've squashed them into the same commit.

**Comment by vimuthm** [comment]
> Do the 'full' upgrade in two steps as @kouyk mentioned or do a minimal one-step upgrade as done in this PR?

The gradle guides suggest running the upgrades separately and following that, I think it makes sense to commit the changes separately as well. One pro of this would be might be easier to track any regressions down the line, though it will be unlikely.

**Review by kouyk — APPROVED** [review]
LGTM. One small query I have is with the 2nd commit message, it is better to phrase it as `reports.*.enabled` changed to `reports.*.required`?

**Review by vimuthm — APPROVED** [review]
LGTM!

**Comment by damithc** [comment]
Thanks for the reviews @kouyk @VimuthM 
@yhtMinceraft1010X can you do the small change @kouyk suggested. After that, we can merge this.

**Comment by yhtMinceraft1010X** [comment]
These are the corresponding PRs for the same change in Duke:
* https://github.com/se-edu/duke/pull/71
* https://github.com/se-edu/duke/pull/70

**Comment by damithc** [comment]
Thanks for your good work @yhtMinceraft1010X

**Pull request merged**
