### PR TITLE
[#214] Fix alignment by changing index font

### LINKED ISSUE #214: Vertically misaligned names in Person List
image

### PR DESCRIPTION
**Pull request by baskargopinath**
Fixes #214 

**Explanation below image**

image

- **Issue:** Alignment problem with index numbers in PersonListCard due to proportional font.
- **Solution:** Changed the index font to Arial Mono, a monospaced font.
- **Font Load:** Added Arial Mono MT Pro Regular font to the project.
- **CSS Update:** Modified `cell_big_index` style to use Arial Mono.
- **FXML Adjustment:** Updated `HBox` and `Label` elements for consistent alignment.
- **Outcome:** Achieved uniform alignment of index numbers, improving the UI appearance.

### CODE REVIEW

**Comment by damithc** [comment]
@baskargopinath If the second commit is simply fixing an error introduced by the first commit, the proper fix is to revise the first commit to not introduce the error at all. That way, we avoid polluting the history with unnecessary commits.

**Comment by baskargopinath** [comment]
Understood prof will fix it asap @damithc

**Comment by damithc** [comment]
@baskargopinath two other comments:

1. It's good enough for the commit message subject to state the WHAT part (no need for the HOW) e.g., `Fix misalignment of person names`. The HOW part can be in the body.
2. The max commit message body width is 72 chars. Looks like yours is unnecessarily narrower than that.

**Comment by baskargopinath** [comment]
@damithc okay ived fixed it prof. I had to delete this repo so i can fork AB3-J17 for 2103R. I have sent the PR from my nus github account instead with the requested changes

**Pull request closed without merging**
