### PR TITLE
Remove unnecessary call to super in inherited classes

### LINKED ISSUE #83: Unnecessary call to super() in StorageManager.java
Hello, the call `super()` within the `StorageManager` class (line 23 -30) seems to be meaningless and could be removed to avoid misunderstanding:
```java
    /**
     * Creates a {@code StorageManager} with the given {@code AddressBookStorage} and {@code UserPrefStorage}.
     */
    public StorageManager(AddressBookStorage addressBookStorage, UserPrefsStorage userPrefsStorage) {
        super();
        this.addressBookStorage = addressBookStorage;
        this.userPrefsStorage = userPrefsStorage;
    }
```
Discussion on this minor issue can be found [here](https://github.com/nus-cs2103-AY2021S2/forum/issues/181).
Thank you.

### PR DESCRIPTION
**Pull request by JinHao-L**
Fixes #83

Removes unnecessary `super()` call in `StorageManager`, `ModelManager` & `UiManager`

### CODE REVIEW

**Comment by damithc** [comment]
Thanks for the PR @JinHao-L 
Probably no need to split into three separate commits?

**Comment by JinHao-L** [comment]
Thanks for the suggestion. I have merged the 3 commits into 1. :+1:

**Review by kouyk — APPROVED** [review]
LGTM, these seem to be all the 3 instances with such an issue.

**Comment by damithc** [comment]
> Thanks for the suggestion. I have merged the 3 commits into 1. 👍

Thanks @JinHao-L Please submit the new version as a new iteration using the CanIHasReview-bot

**Comment by damithc** [comment]
Thanks for the fix @JinHao-L and @kouyk for the review.
Note: I shortened the commit message a bit.

**Pull request merged**
