### PR TITLE
Storage class diagram shows dependencies where associations are needed #93

### LINKED ISSUE #93: Storage class diagram shows dependencies where associations are needed
See https://github.com/nus-cs2103-AY2021S2/forum/issues/305

### PR DESCRIPTION
**Pull request by seanjyjy**
Fixes #93

Updated storage class diagram
StorageClassDiagram

### CODE REVIEW

**Review by JinHao-L — COMMENTED** [review]
LGTM, diagram reflects the dependency relationship between `JsonSerializableAddressBook` and `JsonAdapatedPerson` and between `JsonAdaptedPerson` and `JsonAdpatedTag` 👍

**Review by damithc — CHANGES_REQUESTED** [review]
Thanks for the fix @seanjyjy 
Sorry for the delay in reviewing. 
The change seems correct. Please submit a new version after revising the commit message to follow our conventions https://se-education.org/guides/conventions/git.html
@JinHao-L Thanks for the review. Please also review the commit message in future reviews.

**Comment by damithc** [comment]
@seanjyjy BTW, we can also add multiplicities for those arrows as well, to show that they are collections, not individual objects.

**Comment by seanjyjy** [comment]
Thanks for the review @JinHao-L and @damithc

I have updated the commit message and included the multiplicities for the arrow.

Updated Storage class diagram:
StorageClassDiagram

**Comment by damithc** [comment]
> I have updated the commit message and included the multiplicities for the arrow.

That's good @seanjyjy . When ready, submit a new version using CIHR (as you did above).

Note that commit message has line length limits.

**Review by damithc — CHANGES_REQUESTED** [review]
The code looks fine 👍 

The two commit message subjects are not consistent. e.g., one starts with `DG:`.
I don't mind just one commit for both changes but the commit message should be well-written.

See https://se-education.org/guides/conventions/git.html for examples

**Comment by damithc** [comment]
Thanks for the fix @seanjyjy 
I squashed the commits and rephrased the commit message to make it more compliant with our conventions.

**Pull request merged**
